[project]
name = "ai-logistics-comp-assistant"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Pratap V", email = "vpratapchoudary@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
ai-logistics-comp-assistant = "ai_logistics_comp_assistant:main"

[build-system]
requires = ["uv_build>=0.12.8,<0.13.0"]
build-backend = "uv_build"
